title: Project Overview
description: A detailed look at extending kernel support for CVMFS
remote_theme: mmistakes/minimal-mistakes
paginate: false
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
